### ISSUE TITLE
Expansion of Scope to Include TOC?

### ISSUE THREAD

**Issue by roke-julian-lockhart** [mjbvz/vscode-markdown-yaml-preamble#10]
Currently, all of the Markdown TOC generators, are that - generators. I prefer your implementation to rendering, which is to dynamically render in the Preview Pane by consuming data already present. https://znotes.thedoc.eu.org/note/editor/zettelkasten/?h=contents#table-of-contents does this, yet there is nothing similar for VSCode. Consequently, do you think you could expand the scope of this somewhat to render a TOC too?

**Comment by mjbvz** [comment]
That sounds like a better fit for a dedicated TOC extension

**Comment by roke-julian-lockhart** [comment]
> https://github.com/mjbvz/vscode-markdown-yaml-preamble/issues/10#issuecomment-1853057974

Yeah, @mjbvz, I thought so too. Just, there aren't any, so I thought I might as well try my hand.
