### ISSUE TITLE
Inline Rendering Support

### ISSUE THREAD

**Issue by roke-julian-lockhart** [mjbvz/vscode-markdown-yaml-preamble#12]
1.	#### **Request**

	Instead of forcing the preamble to render at the start of the page, I'd like to be able to instruct the extension to render at an arbitrary, user-defined section of text (for it's merely a table, so it should be trivial to insert). The best method of doing this which I've considered is, for ease, a custom HTML tag (or *perhaps*, for consistency, a class of the `<table>` tag).

1.	#### **Rationale**

	My use case is to be able to render it under a “Metadata” heading at or near the start or end of my documents (I'm yet to decide which). Additionally, if ever https://github.com/mjbvz/vscode-markdown-yaml-preamble/issues/4#issue-1174231163 were implemented, this would be incredibly useful in the event that a significant amount of keypairs are present in the preamble.

**Comment by mjbvz** [comment]
Out of scope for this extension

**Comment by roke-julian-lockhart** [comment]
> https://github.com/mjbvz/vscode-markdown-yaml-preamble/issues/12#issuecomment-2018250089

@mjbvz, why is that?

**Comment by mjbvz** [comment]
Because it adds complication for a niche use case

**Comment by roke-julian-lockhart** [comment]
> https://github.com/mjbvz/vscode-markdown-yaml-preamble/issues/12#issuecomment-2018334019

I suppose what I stated about https://github.com/mjbvz/vscode-markdown-yaml-preamble/issues/4#issue-1174231163 could be solved with a scroll bar anyway.
