### ISSUE TITLE
"markdown.previewFrontMatter" unrecognized setting

### ISSUE THREAD

**Issue by crystalfp** [mjbvz/vscode-markdown-yaml-preamble#2]
Installing the extension on the latest VC version (1.31.0), the documented `"markdown.previewFrontMatter": "show"` is no longer here. Could you update the extension documentation?
Thanks!

**Comment by mjbvz** [comment]
Would you like to submit a PR that updates the readme?

**Comment by rhcarvalho** [comment]
FWIW the setting was removed in commit https://github.com/Microsoft/vscode/commit/1bbc0e3b4dcdcdba4ae8e897e43059bcb90e7db9
